pip install scrapy
pip install pypiwin32
pip install zipcode
pip install bs4
pip install pypostalcode
pip install sqlalchemy
pip install psycopg2
pip install requests
pip install selenium
pip install pyyaml
pip install scrapy-random-useragent
pip install geopy
pip install mapbox
pip install git+https://github.com/duydo/python-mapzen.git
pip install usaddress
pip install googletrans
pip install geocoder
pip install googlemaps
pip install pygeocoder
pip install demjson
pip install nominatim
pip install unicodecsv
pip install scrapy_proxies
